services:
  weather-station-1:
    image: weather-station:1.0
    container_name: weather-station-1
    environment:
      STATION_ID: 1
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: on-failure

  weather-station-2:
    image: weather-station:1.0
    container_name: weather-station-2
    environment:
      STATION_ID: 2
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: on-failure

  rain-processor:
    image: kafka-processor:1.0
    container_name: rain-processor
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: on-failure

  central-station:
    image: central-station:1.0
    container_name: central-station
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_URL: jdbc:postgresql://postgres:5432/weather_db
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
    depends_on:
      - kafka
      - postgres
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    ports:
      - "9092:9092"      # for clients INSIDE the docker network
      - "29092:29092"    # for clients on the HOST (your Java in VS Code)
    environment:
      # KRaft mode — no Zookeeper needed
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      # Single-node settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Cluster ID for KRaft (any base64 22-char string works)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: